-- MOSTRANDO TODOS OS USUÁRIOS QUE NASCERAM ENTRE 1990 ATÉ 2004
SELECT NM_NOME, NM_SOBRENOME, DS_EMAIL, DS_SENHA, NR_TELEFONE, DT_NASCIMENTO 
    FROM T_MTP_USUARIO
  WHERE DT_NASCIMENTO BETWEEN TO_DATE(1990,'YYYY') AND TO_DATE(2004,'YYYY')
  ORDER BY DT_NASCIMENTO ASC;
  
  
-- MOSTRA O HISTÓRICO DE CADA USUÁRIO QUE VISITOM OS POSTOS ELÉTRICOS DA BELA VISTA
SELECT U.NM_NOME, E.CD_HIST_ESTAB, PELE.NM_POSTO_ELETRICO
    FROM T_MTP_USUARIO U LEFT OUTER JOIN T_MTP_HIST_ESTABELECIMENTO E
    ON (U.CD_USUARIO = E.CD_USUARIO)
    LEFT OUTER JOIN T_MTP_HIST_POSTO_ELETRICO ELE
    ON (E.CD_HIST_ESTAB = ELE.CD_HIST_ESTAB)
    LEFT OUTER JOIN T_MTP_POSTO_ELETRICO PELE
    ON (PELE.CD_POSTO_ELETRICO = ELE.CD_POSTO_ELETRICO)
WHERE NM_BAIRRO = 'BELA VISTA'
ORDER BY U.CD_USUARIO ASC;


-- MOSTRA A QUANTIDADE DE ESTRELAS DOS RESTAURANTES E A QUANTIDADE DE RESTAURANTES
SELECT NR_QUANT_ESTRELA AS "Quantidade de estrelas", COUNT(*) as "Quantidade de restaurante"
FROM T_MTP_RESTAURANTE GROUP BY NR_QUANT_ESTRELA;


-- MOSTRA QUANTIDADE TOTAL DE VISITANTES EM UM POSTO DESDE QUE SEJA MAIOR QUE DOIS
SELECT PELE.NM_POSTO_ELETRICO as "Nome do posto", COUNT(U.CD_USUARIO) AS "Visitantes"
    FROM T_MTP_USUARIO U LEFT OUTER JOIN T_MTP_HIST_ESTABELECIMENTO E
    ON (U.CD_USUARIO = E.CD_USUARIO)
    LEFT OUTER JOIN T_MTP_HIST_POSTO_ELETRICO ELE
    ON (E.CD_HIST_ESTAB = ELE.CD_HIST_ESTAB)
    LEFT OUTER JOIN T_MTP_POSTO_ELETRICO PELE
    ON (PELE.CD_POSTO_ELETRICO = ELE.CD_POSTO_ELETRICO)
    GROUP BY PELE.NM_POSTO_ELETRICO
    HAVING COUNT(U.CD_USUARIO) > 2;

  
